[project]
name = "iasis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Konstantinos Zervakis", email = "zervakisai@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
iasis = "iasis:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
