name: CI

on:
  push:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - run: uv sync --locked --all-extras --dev

      - run: uv run ruff check .
      - run: uv run ruff format --check .
      - run: uv run mypy src
